#!usr/bin/env php
<?php

require 'vendor/autoload.php';

use App\Commands\UserSeederCommand;
use Symfony\Component\Console\Application;

$application = new Application;

// $application->add(new SayHelloCommand);
// $application->add(new SayGoodbyeCommand);

$application->add(new UserSeederCommand);

$application->run();
