#!usr/bin/env php
<?php
use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$db = new PDO('mysql:host=alex1447.beget.tech;port=3306;dbname=alex1447_test', 'alex1447_test', 'hellojava');
$faker = Faker\Factory::create();

$application = new Application();

// $application->add(new SayHelloCommand);
// $application->add(new SayGoodbyeCommand);

$application->add(new App\Commands\UserSeederCommand($db, $faker));

$application->run();
